## 1. Import Libraries

In [1]:
import requests
from selenium import webdriver
from time import sleep
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import pandas as pd
import sys
sys.path.append('../')

In [2]:
import src.cleaning_web as fc

## 2. Configure the Selenium tool to be used

In [3]:
opciones= Options()
opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
#para ocultarme como robot, pero me sigue diciendo que hay un software automatico usando chrome
opciones.add_experimental_option('useAutomationExtension', False)
opciones.add_argument('--start-maximized') #empezar maximizado
opciones.add_argument('user.data-dir=selenium') #guarda las cookies
opciones.add_argument('drive/adblock.crx') #adblocker
opciones.add_argument('--incognito')#incognito window

## 3. We start with the web scraping of our data.

### 3.1 We determined the cities to be used, which have been taken from our first Scoring data set.

*para que esta parte quede mejor sería importante exportar las ciudades directamente del csv, y agregarles la barra media a las ciudades que tienen un espacio dentro de su estructura*

In [4]:
cities = ['Aarhus', 'Adelaide', 'Albuquerque', 'Almaty', 'Amsterdam','Anchorage', 'Andorra', 'Ankara', 'Asheville', 'Asuncion','Athens', 'Atlanta', 'Auckland', 'Austin', 'Baku', 'Bali','Baltimore', 'Bangkok', 'Barcelona', 
          'Beijing', 'Beirut','Belfast', 'Belgrade', 'Bengaluru', 'Bergen','Berlin', 'Bern', 'Bilbao', 
          'Birmingham', 'Bogota', 'Boise','Bologna', 'Bordeaux', 'Boston', 'Boulder', 'Bozeman','Bratislava', 
          'Brighton', 'Brisbane', 'Bristol', 'Brno','Brussels', 'Bucharest', 'Budapest', 'Buenos-Aires', 'Buffalo',
          'Cairo', 'Calgary', 'Cambridge', 'cape-town', 'Caracas', 'Cardiff','Casablanca', 'Charleston', 'Charlotte', 
          'Chattanooga', 'Chennai','Chiang-Mai', 'Chicago', 'Chisinau', 'Christchurch', 'Cincinnati',
       'Cleveland', 'Cluj-Napoca', 'Cologne', 'Colorado-Springs','Columbus', 'Copenhagen', 'Cork', 'Curitiba', 'Dallas',
       'Dar-es-Salaam', 'Delhi', 'Denver', 'Des-Moines', 'Detroit','Doha', 'Dresden', 'Dubai', 'Dublin', 'Dusseldorf', 'Edinburgh',
       'Edmonton', 'Eindhoven', 'Eugene', 'Florence', 'Florianopolis','Fort-Collins', 'Frankfurt', 'Fukuoka', 'Gdansk',
       'Geneva', 'Gibraltar', 'Glasgow', 'Gothenburg', 'Grenoble','Guadalajara', 'Guatemala-City', 'Halifax', 'Hamburg', 'Hannover',
       'Havana', 'Helsinki', 'Ho-Chi-Minh-City', 'Hong-Kong', 'Honolulu','Houston', 'Hyderabad', 'Indianapolis', 'Innsbruck', 'Istanbul',
       'Jacksonville', 'Jakarta', 'Johannesburg', 'Kansas-City','Karlsruhe', 'Kathmandu', 'Kiev', 'Kingston', 'Knoxville',
       'Krakow', 'Kuala-Lumpur', 'Kyoto', 'Lagos', 'La-Paz','Las-Palmas-de-Gran-Canaria', 'Las-Vegas', 'Lausanne', 'Leeds',
       'Leipzig', 'Lille', 'Lima', 'Lisbon', 'Liverpool', 'Ljubljana','London', 'Los-Angeles', 'Louisville', 'Luxembourg', 'Lviv',
       'Lyon', 'Madison', 'Madrid', 'Malaga', 'Malmo', 'Managua','Manchester', 'Manila', 'Marseille', 'Medellin', 'Melbourne',
       'Memphis', 'Mexico-City', 'Miami', 'Milan', 'Milwaukee','Minneapolis-Saint-Paul', 'Minsk', 'Montevideo', 'Montreal',
       'Moscow', 'Mumbai', 'Munich', 'Nairobi', 'Nantes', 'Naples','Nashville', 'New-Orleans', 'New-York', 'Nice', 'Nicosia',
       'Oklahoma-City', 'Omaha', 'Orlando', 'Osaka', 'Oslo', 'Ottawa','Oulu', 'Oxford', 'Palo-Alto', 'Panama', 'Paris', 'Perth',
       'Philadelphia', 'Phnom-Penh', 'Phoenix', 'Phuket', 'Pittsburgh','Portland-or', 'Porto', 'Porto-Alegre', 'Prague', 'Providence',
       'Quebec', 'Quito', 'Raleigh', 'Reykjavik', 'Richmond', 'Riga','Rio-De-Janeiro', 'Riyadh', 'Rochester', 'Rome', 'Rotterdam',
       'Saint-Petersburg', 'Salt-Lake-City', 'San-Antonio', 'San-Diego','San-Francisco-Bay-Area', 'San-Jose', 'San-Juan',
       'San-Luis-Obispo', 'San-Salvador', 'Santiago', 'Santo-Domingo','Sao-Paulo', 'Sarajevo', 'Saskatoon', 'Seattle', 'Seoul',
       'Seville', 'Shanghai', 'Singapore', 'Skopje', 'Sofia', 'St-Louis','Stockholm', 'Stuttgart', 'Sydney', 'Taipei', 'Tallinn',
       'Tampa-Bay-Area', 'Tampere', 'Tartu', 'Tashkent', 'Tbilisi','Tehran', 'Tel-Aviv', 'The-Hague', 'Thessaloniki', 'Tokyo',
       'Toronto', 'Toulouse', 'Tunis', 'Turin', 'Turku', 'Uppsala','Utrecht', 'Valencia', 'Valletta', 'Vancouver', 'Victoria',
       'Vienna', 'Vilnius', 'Warsaw', 'Washington-dc', 'Wellington','Winnipeg', 'Wroclaw', 'Yerevan', 'Zagreb', 'Zurich']

In [5]:
'Winnipeg'.lower()

'winnipeg'

In [6]:
cities_lower = []
for i in cities:
    cities_lower.append(i.lower())

In [7]:
#cities_lower

#### We will generate the URL to be used for our data collection.

In [8]:
url_list = []
for i in cities_lower:
    url_list.append(f"https://teleport.org/cities/{i}/")

In [9]:
#url_list

In [10]:
len(url_list)

262

### Mediante Webscrapping guardamos la Descripción de cada ciudad

In [58]:
driver = webdriver.Chrome(ChromeDriverManager().install())
Description = []
for i in url_list:
    driver.get(i)
    sleep(5)
    my_info = driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(1) > div:nth-child(3) > div > div.summary___1Tz89").text
    Description.append(my_info)
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-58-39fbbb61f52f>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
<ipython-input-58-39fbbb61f52f>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  my_info = driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(1) > div:nth-child(3) > div > div.summary___1Tz89").text

In [59]:
len(Description)

262

### Ahora intentaremos obtener el Housing cost, con cada tipo de apartamento

In [169]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

housing = []
        
for i in url_list:
    driver.get(i)
    sleep(5)
    dicc_hou ={"Large_apartment" : "No hay dato",
               "Medium_apartment" :"No hay dato",
               "Small_apartment":"No hay dato",
               "url":i}
    try:
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select").click()
        driver.implicitly_wait(20)
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select > option:nth-child(1)").click()
        Large_price=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > div.number___2Gtf5").text
        dicc_hou["Large_apartment"] = Large_price
        driver.implicitly_wait(20)
    except:
        pass
        
    try:
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select").click()
        driver.implicitly_wait(20)
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select > option:nth-child(2)").click()
        Medium_price=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > div.number___2Gtf5").text
        dicc_hou["Medium_apartment"] = Medium_price
        driver.implicitly_wait(20)
    except:
        pass
        
    try:
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select").click()
        driver.implicitly_wait(20)
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select > option:nth-child(3)").click()
        Small_price=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > div.number___2Gtf5").text
        dicc_hou["Small_apartment"] = Small_price
        driver.implicitly_wait(20)
    except:
        pass

    housing.append(dicc_hou)
        
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-169-e4ab0a4775f4>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-169-e4ab0a4775f4>:11: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select").click()
<ipython-input-169-e4ab0a4775f4>:13: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select > option:nth-child(1)").click()
<ipython-input-169-e4ab0a4775f4>:14: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Large_price=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > div.number___2Gtf5").text
<ipython-input-169-e4ab0a4775f4>:18: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select").click()
<ipython-input-169-e4ab0a4775f4>:20: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select > option:nth-child(2)").click()
<ipython-input-169-e4ab0a4775f4>:21: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Medium_price=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > div.number___2Gtf5").text
<ipython-input-169-e4ab0a4775f4>:25: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select").click()
<ipython-input-169-e4ab0a4775f4>:27: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > select > option:nth-child(3)").click()
<ipython-input-169-e4ab0a4775f4>:28: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Small_price=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div.details___3QNKe > div.number___2Gtf5").text

In [63]:
len(housing)

262

In [65]:
#housing

### Ahora intentaremos obtener los datos del Daily Living Cost

In [33]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

#Daily_living_cost
Daily_living_cost = []

#Monthly_Fitness_Club_Membership = []
#Beer = []
#Monthly_Public_Transport= []
#Lunch = []

for i in url_list:
    if i != 'https://teleport.org/cities/palo-alto/':
        driver.get(i)
        sleep(5)
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > div > h3").click()
        driver.implicitly_wait(20)
        dicc_dlc ={"Monthly_Fitness_Club_Membership" : "No hay dato",
                   "Beer" :"No hay dato",
                   "Monthly_Public_Transport":"No hay dato",
                   "Lunch":"No hay dato",
                   "url":i}
        try:
            Beer_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(3) > td").text
            dicc_dlc["Beer"] = Beer_info
            driver.implicitly_wait(20)
        except:
            pass

        try:
            Lunch_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(7) > td").text
            dicc_dlc["Lunch"] = Lunch_info
            driver.implicitly_wait(20)
        except:
            pass

        try:
            Fitness_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(8) > td").text
            dicc_dlc["Monthly_Fitness_Club_Membership"] = Fitness_info
            driver.implicitly_wait(20)
        except:
            pass

        try:
            Transport_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(9) > td").text
            dicc_dlc["Monthly_Public_Transport"] = Transport_info
            driver.implicitly_wait(20)
        except:
            pass
        
        Daily_living_cost.append(dicc_dlc)
        
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-33-f475d23f8bc1>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-33-f475d23f8bc1>:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > div > h3").click()
<ipython-input-33-f475d23f8bc1>:23: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Beer_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(3) > td").text
<ipython-input-33-f475d23f8bc1>:30: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Lunch_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(7) > td").text
<ipython-input-33-f475d23f8bc1>:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Fitness_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(8) > td").text
<ipython-input-33-f475d23f8bc1>:44: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Transport_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(3) > table > tbody > tr:nth-child(9) > td").text

In [37]:
len(Daily_living_cost)

261

*Aqui me faltaria la información de Palo Alto que no cuenta esta información. Una opción para que mi tabla no pierda los números de Palo Alto es crear un diccionario vacio y agregarlo a la lista*

### Recolectamos las variables Travel, Safety & Education

In [78]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

#Travel_Connectivity
#Safety
#Education
Travel_Safety_Education = []

#Airport_hub = []
#Intercity_train_connectivity= []
#Gun_related_deaths = []
#Guns_per_residents= []
#Pisa_ranking = []
#Best_university = []

for i in url_list:
    driver.get(i)
    sleep(5)
    dicc_tse ={"Airport_hub" : "No hay dato",
               "Intercity_train_connectivity" :"No hay dato",
               "Gun_related_deaths":"No hay dato",
               "Guns_per_residents": "No hay dato",
               "Pisa_ranking":"No hay dato",
               "Best_university":"No hay dato",
               "url":i}
    if i != 'https://teleport.org/cities/palo-alto/':
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(6) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            Airpot_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(6) > table > tbody > tr:nth-child(1) > td").text
            dicc_tse["Airport_hub"] = Airpot_info
            driver.implicitly_wait(20) 
        except:
            pass
        try:
            Train_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(6) > table > tbody > tr:nth-child(3) > td").text
            dicc_tse["Intercity_train_connectivity"] = Train_info
            driver.implicitly_wait(20)
        except:
            pass
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(9) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            Deaths_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(9) > table > tbody > tr:nth-child(2) > td").text
            dicc_tse["Gun_related_deaths"] = Deaths_info
            driver.implicitly_wait(20)
        except:
            pass
        try:
            Guns_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(9) > table > tbody > tr:nth-child(3) > td").text
            dicc_tse["Guns_per_residents"] = Guns_info
            driver.implicitly_wait(20)  
        except:
            pass
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(11) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            Pisa_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(11) > table > tbody > tr:nth-child(7) > td").text
            dicc_tse["Pisa_ranking"] = Pisa_info
            driver.implicitly_wait(20)
        except:
            pass
        try:
            University_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(11) > table > tbody > tr:nth-child(1) > td").text
            dicc_tse["Best_university"] = University_info
            driver.implicitly_wait(20)         
        except:
            pass

    Travel_Safety_Education.append(dicc_tse)   
    
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-78-a088c9455dd7>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-78-a088c9455dd7>:26: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(6) > div > h3").click()
<ipython-input-78-a088c9455dd7>:29: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Airpot_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(6) > table > tbody > tr:nth-child(1) > td").text
<ipython-input-78-a088c9455dd7>:35: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Train_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(6) > table > tbody > tr:nth-child(3) > td").text
<ipython-input-78-a088c9455dd7>:40: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(9) > div > h3").click()
<ipython-input-78-a088c9455dd7>:43: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Deaths_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(9) > table > tbody > tr:nth-child(2) > td").text
<ipython-input-78-a088c9455dd7>:49: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Guns_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(9) > table > tbody > tr:nth-child(3) > td").text
<ipython-input-78-a088c9455dd7>:54: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(11) > div > h3").click()
<ipython-input-78-a088c9455dd7>:57: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Pisa_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(11) > table > tbody > tr:nth-child(7) > td").text
<ipython-input-78-a088c9455dd7>:63: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  University_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(11) > table > tbody > tr:nth-child(1) > td").text

In [80]:
len(Travel_Safety_Education)

262

In [82]:
data = Daily_living_cost + Travel_Safety_Education + housing

In [86]:
df = pd.DataFrame(data)

In [87]:
df.head()

,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,url,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,Large_apartment,Medium_apartment,Small_apartment
0,$37.00,$1.70,$62.00,$15.00,https://teleport.org/cities/aarhus/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,$50.00,$4.30,$80.00,$13.00,https://teleport.org/cities/adelaide/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,$52.00,$2.90,$37.00,$12.00,https://teleport.org/cities/albuquerque/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,$83.00,$0.68,$19.00,$5.70,https://teleport.org/cities/almaty/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,$49.00,$2.10,$100.00,$18.00,https://teleport.org/cities/amsterdam/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
df.shape

(785, 14)

In [90]:
data2 = Travel_Safety_Education

In [93]:
data3 = Daily_living_cost

In [91]:
df2 = pd.DataFrame(data2)

In [92]:
df2.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/

In [94]:
df3 = pd.DataFrame(data3)

In [95]:
df4 = df2.join(df3, lsuffix="_uno", rsuffix="_otro")

In [96]:
df4.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,url_otro
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,$15.00,https://teleport.org/cities/aarhus/
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,$13.00,https://teleport.org/cities/adelaide/
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,$12.00,https://teleport.org/cities/albuquerque/
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,$5.70,https://teleport.org/cities/almaty/
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,$18.00,https://teleport.org/cities/amsterdam/

In [97]:
data4= housing

In [98]:
df5 = pd.DataFrame(data4)

In [99]:
df5.head()

,Large_apartment,Medium_apartment,Small_apartment,url
0,$1700,$1300,$840,https://teleport.org/cities/aarhus/
1,$1500,$1200,$1000,https://teleport.org/cities/adelaide/
2,$1200,$950,$760,https://teleport.org/cities/albuquerque/
3,$620,$480,$340,https://teleport.org/cities/almaty/
4,$2400,$2000,$1600,https://teleport.org/cities/amsterdam/

In [ ]:
df6 = df4.join(df5, lsuffix="_uno", rsuffix="_otro")

In [102]:
df6.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,url_otro,Large_apartment,Medium_apartment,Small_apartment,url
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,$15.00,https://teleport.org/cities/aarhus/,$1700,$1300,$840,https://teleport.org/cities/aarhus/
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,$13.00,https://teleport.org/cities/adelaide/,$1500,$1200,$1000,https://teleport.org/cities/adelaide/
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,$12.00,https://teleport.org/cities/albuquerque/,$1200,$950,$760,https://teleport.org/cities/albuquerque/
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,$5.70,https://teleport.org/cities/almaty/,$620,$480,$340,https://teleport.org/cities/almaty/
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,$18.00,https://teleport.org/cities/amsterdam/,$2400,$2000,$1600,https://teleport.org/cities/amsterdam/

In [103]:
df7 = df6.copy()

In [105]:
df7["cities"] = cities

In [106]:
df7.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,url_otro,Large_apartment,Medium_apartment,Small_apartment,url,cities
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,$15.00,https://teleport.org/cities/aarhus/,$1700,$1300,$840,https://teleport.org/cities/aarhus/,Aarhus
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,$13.00,https://teleport.org/cities/adelaide/,$1500,$1200,$1000,https://teleport.org/cities/adelaide/,Adelaide
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,$12.00,https://teleport.org/cities/albuquerque/,$1200,$950,$760,https://teleport.org/cities/albuquerque/,Albuquerque
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,$5.70,https://teleport.org/cities/almaty/,$620,$480,$340,https://teleport.org/cities/almaty/,Almaty
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,$18.00,https://teleport.org/cities/amsterdam/,$2400,$2000,$1600,https://teleport.org/cities/amsterdam/,Amsterdam

In [108]:
df7["Description"] = Description

In [109]:
df7.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,url_otro,Large_apartment,Medium_apartment,Small_apartment,url,cities,Description
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,$15.00,https://teleport.org/cities/aarhus/,$1700,$1300,$840,https://teleport.org/cities/aarhus/,Aarhus,"Aarhus, Denmark, is among the top cities with ..."
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,$13.00,https://teleport.org/cities/adelaide/,$1500,$1200,$1000,https://teleport.org/cities/adelaide/,Adelaide,"Adelaide, Australia, is among the top cities w..."
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,$12.00,https://teleport.org/cities/albuquerque/,$1200,$950,$760,https://teleport.org/cities/albuquerque/,Albuquerque,"Albuquerque, New Mexico, is among the top citi..."
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,$5.70,https://teleport.org/cities/almaty/,$620,$480,$340,https://teleport.org/cities/almaty/,Almaty,"Almaty, Kazakhstan, differentiates itself with..."
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,$18.00,https://teleport.org/cities/amsterdam/,$2400,$2000,$1600,https://teleport.org/cities/amsterdam/,Amsterdam,Amsterdam is one of the most bike-friendly cit...

### Población:

In [ ]:
def funcion_poblacion(lista):
    resultado=[]
    try:
        for i in lista:
            res = requests.get(i)
            soup = BeautifulSoup(res.content,"html.parser")
            textaco = soup.findAll("div", {"class":"figureLabel___2OYTW"})
            resultado.append(textaco[0].getText())
    except:
        resultado.append("No hay dato")
    return resultado

In [190]:
Poblacion = funcion_poblacion(url_list)

In [191]:
len(Poblacion)

262

In [199]:
df7["Poblacion"] = Poblacion

In [200]:
df7.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,url_otro,Large_apartment,Medium_apartment,Small_apartment,url,cities,Description,Poblacion
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,$15.00,https://teleport.org/cities/aarhus/,$1700,$1300,$840,https://teleport.org/cities/aarhus/,Aarhus,"Aarhus, Denmark, is among the top cities with ...","250,200"
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,$13.00,https://teleport.org/cities/adelaide/,$1500,$1200,$1000,https://teleport.org/cities/adelaide/,Adelaide,"Adelaide, Australia, is among the top cities w...","1,708,700"
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,$12.00,https://teleport.org/cities/albuquerque/,$1200,$950,$760,https://teleport.org/cities/albuquerque/,Albuquerque,"Albuquerque, New Mexico, is among the top citi...","630,800"
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,$5.70,https://teleport.org/cities/almaty/,$620,$480,$340,https://teleport.org/cities/almaty/,Almaty,"Almaty, Kazakhstan, differentiates itself with...","2,029,800"
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,$18.00,https://teleport.org/cities/amsterdam/,$2400,$2000,$1600,https://teleport.org/cities/amsterdam/,Amsterdam,Amsterdam is one of the most bike-friendly cit...,"2,628,100"

### Exportaremos los datos conseguidos hasta el momento, para resguardarlos como primera copia.

In [110]:
!pwd

/Users/danielaarias/Ironhack/Choose-to-live-better/Notebooks

In [111]:
df7.to_csv("../Data/primer_web_scrapping.csv")

### Ahora lo intentemos con los trabajos

In [116]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

Jobs = []
jobs_list = []
salary_list = []

for i in url_list[:3]:
    driver.get(i)
    sleep(5)
    dicc_job ={"Types" : "No hay dato",
               "Median_salary" :"No hay dato",
               "url":i}
    try:
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(5) > div:nth-child(3) > div.role___2yJlf > select").click()
        driver.implicitly_wait(20)
        for p in range(1,54):
            try:
                jobs_list.append((driver.find_element_by_css_selector(f"#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(5) > div:nth-child(3) > div.role___2yJlf > select > option:nth-child({p})").text)
                driver.find_element_by_css_selector(f"#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(5) > div:nth-child(3) > div.role___2yJlf > select > option:nth-child({p})").click()
                driver.implicitly_wait(20)
                salary_list.append(driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(5) > div:nth-child(3) > div.details___UOsq6 > div.median___3Tlcr > div.value___2zt_y").text)
                driver.implicitly_wait(20)
            except:
                pass
    except:
        pass

    Jobs.append(dicc_job)
        
driver.quit()

SyntaxError: invalid syntax (<ipython-input-116-c01bc275aa9d>, line 19)

In [114]:
Jobs

[{'Types': 'No hay dato',
  'Median_salary': 'No hay dato',
  'url': 'https://teleport.org/cities/aarhus/'},
 {'Types': 'No hay dato',
  'Median_salary': 'No hay dato',
  'url': 'https://teleport.org/cities/adelaide/'},
 {'Types': 'No hay dato',
  'Median_salary': 'No hay dato',
  'url': 'https://teleport.org/cities/albuquerque/'}]

In [115]:
jobs_list

[]

In [ ]:
salary_info=(driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(5) > div:nth-child(3) > div.details___UOsq6 > div.median___3Tlcr > div.value___2zt_y").text)
dicc_job["Median_salary"] = salary_info

### Dejaremos en segundo plano los tipos de trabajo y su salario medio, ya que necesitamos indagar el tema del scroll para obtener los datos

## Tolerance, Taxation, People,  Good Country Index, Environmental quality

In [223]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

#Tolerance
#Taxation
#Leisure&Culture
#Economy
ttge = []


for i in url_list:
    driver.get(i)
    sleep(5)
    dicc_ttge ={"Homosexuality_acceptance" : "No hay dato",
               "LGBT_adoption_rights" :"No hay dato",
               "LGBT_homosexuality_rights":"No hay dato",
               "LGBT_marriage_rights": "No hay dato",
               "VAT_Sales_Tax":"No hay dato",
               "Art_galleries":"No hay dato",
               "Concert_venues":"No hay dato",
               "Museums":"No hay dato",
               "Sport_venues": "No hay dato",
               "Currency_for_urban_area": "No hay dato",
               "GDP_per_capita":"No hay dato",
               "url":i}
    
    if i != 'https://teleport.org/cities/palo-alto/':
        
        #Tolerance
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            homosex_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(1) > td").text
            dicc_ttge["Homosexuality_acceptance"] = homosex_info
            driver.implicitly_wait(20) 
        except:
            pass
        try:
            adoption_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(4) > td").text
            dicc_ttge["LGBT_adoption_rights"] = adoption_info
            driver.implicitly_wait(20)
        except:
            pass
        try:
            rights_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(11) > td").text
            dicc_ttge["LGBT_homosexuality_rights"] = rights_info
            driver.implicitly_wait(20)
        except:
            pass
        try:
            marriage_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(13) > td").text
            dicc_ttge["LGBT_marriage_rights"] = marriage_info
            driver.implicitly_wait(20)
        except:
            pass
        
        #Taxation
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(14) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            VAT_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(14) > table > tbody > tr:nth-child(5) > td").text
            dicc_ttge["VAT_Sales_Tax"] = VAT_info
            driver.implicitly_wait(20)
        except:
            pass
        
        #Leisure&Culture
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            art_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(1) > td").text
            dicc_ttge["Art_galleries"] = art_info
            driver.implicitly_wait(20)  
        except:
            pass
        try:
            concert_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(7) > td").text
            dicc_ttge["Concert_venues"] = concert_info
            driver.implicitly_wait(20)
        except:
            pass
        try:
            museums_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(11) > td").text
            dicc_ttge["Museums"] = museums_info
            driver.implicitly_wait(20)         
        except:
            pass
        try:
            sport_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(15) > td").text
            dicc_ttge["Sport_venues"] = sport_info
            driver.implicitly_wait(20)
        except:
            pass
        
        #Economy
        driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(13) > div > h3").click()
        driver.implicitly_wait(20)
        try:
            currency_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(13) > table > tbody > tr:nth-child(2) > td").text
            dicc_ttge["Currency_for_urban_area"] = currency_info
            driver.implicitly_wait(20)         
        except:
            pass
        try:
            GDP_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(13) > table > tbody > tr:nth-child(5) > td").text
            dicc_ttge["GDP_per_capita"] = GDP_info
            driver.implicitly_wait(20)         
        except:
            pass

    ttge.append(dicc_ttge)
    
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-223-6757c7f02104>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-223-6757c7f02104>:29: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > div > h3").click()
<ipython-input-223-6757c7f02104>:32: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  homosex_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(1) > td").text
<ipython-input-223-6757c7f02104>:38: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  adoption_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(4) > td").text
<ipython-input-223-6757c7f02104>:44: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  rights_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(11) > td").text
<ipython-input-223-6757c7f02104>:50: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  marriage_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(17) > table > tbody > tr:nth-child(13) > td").text
<ipython-input-223-6757c7f02104>:57: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(14) > div > h3").click()
<ipython-input-223-6757c7f02104>:60: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  VAT_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(14) > table > tbody > tr:nth-child(5) > td").text
<ipython-input-223-6757c7f02104>:67: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > div > h3").click()
<ipython-input-223-6757c7f02104>:70: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  art_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(1) > td").text
<ipython-input-223-6757c7f02104>:76: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  concert_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(7) > td").text
<ipython-input-223-6757c7f02104>:82: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  museums_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(11) > td").text
<ipython-input-223-6757c7f02104>:88: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  sport_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(16) > table > tbody > tr:nth-child(15) > td").text
<ipython-input-223-6757c7f02104>:95: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(13) > div > h3").click()
<ipython-input-223-6757c7f02104>:98: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  currency_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(13) > table > tbody > tr:nth-child(2) > td").text
<ipython-input-223-6757c7f02104>:104: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GDP_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(2) > div.contents___mczKq > section:nth-child(13) > table > tbody > tr:nth-child(5) > td").text

In [224]:
len(ttge)

262

In [227]:
#ttge

In [229]:
df8 = pd.DataFrame(ttge)

In [230]:
df8.head()

,Homosexuality_acceptance,LGBT_adoption_rights,LGBT_homosexuality_rights,LGBT_marriage_rights,VAT_Sales_Tax,Art_galleries,Concert_venues,Museums,Sport_venues,Currency_for_urban_area,GDP_per_capita,url
0,93.03,✔ Equal,✔ Sexual orientation and gender identity,0.99,0.25,51,95,18,21,DKK,$44342.66,https://teleport.org/cities/aarhus/
1,0.79,N/A,✔ Legal,Varies by Region,0.10,82,89,37,91,AUD,$46433.30,https://teleport.org/cities/adelaide/
2,93.13,✔ Equal,✔ Sexual orientation and gender identity,0.45,0.07,127,99,35,10,USD,$54596.65,https://teleport.org/cities/albuquerque/
3,66.56,✔ Equal,Ambiguous,0.64,0.12,61,68,24,53,KZT,$24019.95,https://teleport.org/cities/almaty/
4,97.37,✔ Equal,✔ Sexual orientation and gender identity,0.67,0.21,284,339,187,154,EUR,$47354.53,https://teleport.org/cities/amsterdam/

In [228]:
#df7.head()

In [231]:
df9 = df7.join(df8, lsuffix="_uno", rsuffix="_otro")

/usr/local/Caskroom/miniconda/base/envs/ironhack2/lib/python3.8/site-packages/pandas/core/frame.py:9130: FutureWarning: Passing 'suffixes' which cause duplicate columns {'url_uno'} in the result is deprecated and will raise a MergeError in a future version.
  return merge(

In [232]:
df9.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,...,LGBT_homosexuality_rights,LGBT_marriage_rights,VAT_Sales_Tax,Art_galleries,Concert_venues,Museums,Sport_venues,Currency_for_urban_area,GDP_per_capita,url_otro
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,...,✔ Sexual orientation and gender identity,0.99,0.25,51,95,18,21,DKK,$44342.66,https://teleport.org/cities/aarhus/
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,...,✔ Legal,Varies by Region,0.10,82,89,37,91,AUD,$46433.30,https://teleport.org/cities/adelaide/
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,...,✔ Sexual orientation and gender identity,0.45,0.07,127,99,35,10,USD,$54596.65,https://teleport.org/cities/albuquerque/
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,...,Ambiguous,0.64,0.12,61,68,24,53,KZT,$24019.95,https://teleport.org/cities/almaty/
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,...,✔ Sexual orientation and gender identity,0.67,0.21,284,339,187,154,EUR,$47354.53,https://teleport.org/cities/amsterdam/

In [233]:
df9.to_csv("../Data/segundo_web_scrapping.csv")

### Seguimos recolectando datitos

#### Growth_in_2015_2020

In [ ]:
#Esto es una prueba que luego debe ser borrada

In [22]:
url_9 = 'https://teleport.org/cities/zurich/'

In [23]:
res = requests.get(url_9)

In [24]:
soup = BeautifulSoup(res.content,"html.parser")

In [25]:
textaco = soup.findAll("div", {"class":"figureLabel___2OYTW"})

In [29]:
textaco[8].getText()

'60'

In [ ]:
##Puedo agregar a este bucle la variable "Población"

In [44]:
demo=[]
    
for i in url_list:
    dicc_demogra={'Growth':'No hay dato','GDP_per_capita': 'No hay dato','Unemployment': 'No hay dato', 'url':i}
    try:
        res = requests.get(i)
        soup = BeautifulSoup(res.content,"html.parser")
        textaco = soup.findAll("div", {"class":"figureLabel___2OYTW"})
        dicc_demogra["Growth"] = textaco[2].getText()
    except:
        pass
                  
    try:
        dicc_demogra["GDP_per_capita"] = textaco[6].getText()
    except:
        pass
                  
    try:
        dicc_demogra["Unemployment"] = textaco[7].getText()
    except:
        pass
                
    demo.append(dicc_demogra)

In [46]:
len(demo)

262

In [47]:
df10 = pd.DataFrame(demo)

In [48]:
df10

,Growth,GDP_per_capita,Unemployment,url
0,5%,"$44,343",4%,https://teleport.org/cities/aarhus/
1,7%,"$46,433",6%,https://teleport.org/cities/adelaide/
2,7%,"$54,597",5%,https://teleport.org/cities/albuquerque/
3,9%,"$24,020",6%,https://teleport.org/cities/almaty/
4,3%,"$47,355",6%,https://teleport.org/cities/amsterdam/
...,...,...,...,...
257,3%,"$44,843",7%,https://teleport.org/cities/winnipeg/
258,-1%,"$25,105",10%,https://teleport.org/cities/wroclaw/
259,2%,"$7,374",18%,https://teleport.org/cities/yerevan/
260,1%,"$20,889",16%,https://teleport.org/cities/zagreb/
261,6%,"$58,087",3%,https://teleport.org/cities/zurich/

In [55]:
df9 = pd.read_csv("../Data/segundo_web_scrapping.csv")

In [62]:
df9.columns

Index(['Unnamed: 0', 'Airport_hub', 'Intercity_train_connectivity',
       'Gun_related_deaths', 'Guns_per_residents', 'Pisa_ranking',
       'Best_university', 'url_uno', 'Monthly_Fitness_Club_Membership', 'Beer',
       'Monthly_Public_Transport', 'Lunch', 'url_otro', 'Large_apartment',
       'Medium_apartment', 'Small_apartment', 'url_uno.1', 'cities',
       'Description', 'Poblacion', 'Homosexuality_acceptance',
       'LGBT_adoption_rights', 'LGBT_homosexuality_rights',
       'LGBT_marriage_rights', 'VAT_Sales_Tax', 'Art_galleries',
       'Concert_venues', 'Museums', 'Sport_venues', 'Currency_for_urban_area',
       'GDP_per_capita', 'url_otro.1'],
      dtype='object')

In [59]:
df9.reset_index(drop=True)

,Unnamed: 0,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,...,LGBT_homosexuality_rights,LGBT_marriage_rights,VAT_Sales_Tax,Art_galleries,Concert_venues,Museums,Sport_venues,Currency_for_urban_area,GDP_per_capita,url_otro.1
0,0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,...,✔ Sexual orientation and gender identity,0.99,0.25,51,95,18,21,DKK,$44342.66,https://teleport.org/cities/aarhus/
1,1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,...,✔ Legal,Varies by Region,0.10,82,89,37,91,AUD,$46433.30,https://teleport.org/cities/adelaide/
2,2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,...,✔ Sexual orientation and gender identity,0.45,0.07,127,99,35,10,USD,$54596.65,https://teleport.org/cities/albuquerque/
3,3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,...,Ambiguous,0.64,0.12,61,68,24,53,KZT,$24019.95,https://teleport.org/cities/almaty/
4,4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,...,✔ Sexual orientation and gender identity,0.67,0.21,284,339,187,154,EUR,$47354.53,https://teleport.org/cities/amsterdam/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,257,23,0.12,2,31,5,University of Manitoba,https://teleport.org/cities/winnipeg/,$27.00,$0.93,...,✔ Legal,✔ Legal,0.05,58,62,22,26,CAD,$44843.44,https://teleport.org/cities/winnipeg/
258,258,31,0.24,0,1,10,518.54,https://teleport.org/cities/wroclaw/,$57.00,$0.89,...,✔ Legal,✖ Unrecognized,0.23,53,33,32,10,PLN,$25105.40,https://teleport.org/cities/wroclaw/
259,259,35,0.13,1,13,No hay dato,No hay dato,https://teleport.org/cities/yerevan/,$45.00,$1.50,...,✖ No protections,0.87,0.20,83,89,66,22,AMD,$7373.53,https://teleport.org/cities/yerevan/
260,260,27,0.21,3,22,22,480.08,https://teleport.org/cities/zagreb/,$100.00,$2.40,...,✔ Sexual orientation and gender identity,0.77,0.25,94,70,52,35,HRK,$20888.82,https://teleport.org/cities/zagreb/
261,261,137,0.94,3,24,11,ETH Zurich – Swiss Federal Institute of Techno...,https://teleport.org/cities/zurich/,NaN,NaN,...,✔ Sexual orientation and gender identity,0.92,0.08,89,125,99,49,CHF,$58087.21,https://teleport.org/cities/zurich/

In [64]:
df9.drop(["Unnamed: 0", "url_otro", "url_uno.1","url_otro.1"], axis=1, inplace=True)

In [65]:
df9.columns

Index(['Airport_hub', 'Intercity_train_connectivity', 'Gun_related_deaths',
       'Guns_per_residents', 'Pisa_ranking', 'Best_university', 'url_uno',
       'Monthly_Fitness_Club_Membership', 'Beer', 'Monthly_Public_Transport',
       'Lunch', 'Large_apartment', 'Medium_apartment', 'Small_apartment',
       'cities', 'Description', 'Poblacion', 'Homosexuality_acceptance',
       'LGBT_adoption_rights', 'LGBT_homosexuality_rights',
       'LGBT_marriage_rights', 'VAT_Sales_Tax', 'Art_galleries',
       'Concert_venues', 'Museums', 'Sport_venues', 'Currency_for_urban_area',
       'GDP_per_capita'],
      dtype='object')

In [66]:
df11 = df9.join(df10, lsuffix="_uno", rsuffix="_otro")

In [67]:
df11.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,url_uno,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,...,Art_galleries,Concert_venues,Museums,Sport_venues,Currency_for_urban_area,GDP_per_capita_uno,Growth,GDP_per_capita_otro,Unemployment,url
0,8,0.59,1,12,13,Aarhus University,https://teleport.org/cities/aarhus/,$37.00,$1.70,$62.00,...,51,95,18,21,DKK,$44342.66,5%,"$44,343",4%,https://teleport.org/cities/aarhus/
1,26,0.17,1,24,16,University of Adelaide,https://teleport.org/cities/adelaide/,$50.00,$4.30,$80.00,...,82,89,37,91,AUD,$46433.30,7%,"$46,433",6%,https://teleport.org/cities/adelaide/
2,23,0.11,16,328,24,University of New Mexico,https://teleport.org/cities/albuquerque/,$52.00,$2.90,$37.00,...,127,99,35,10,USD,$54596.65,7%,"$54,597",5%,https://teleport.org/cities/albuquerque/
3,45,0.66,1,1,39,427.97,https://teleport.org/cities/almaty/,$83.00,$0.68,$19.00,...,61,68,24,53,KZT,$24019.95,9%,"$24,020",6%,https://teleport.org/cities/almaty/
4,237,0.68,1,4,10,University of Amsterdam,https://teleport.org/cities/amsterdam/,$49.00,$2.10,$100.00,...,284,339,187,154,EUR,$47354.53,3%,"$47,355",6%,https://teleport.org/cities/amsterdam/

In [69]:
df11.columns

Index(['Airport_hub', 'Intercity_train_connectivity', 'Gun_related_deaths',
       'Guns_per_residents', 'Pisa_ranking', 'Best_university', 'url_uno',
       'Monthly_Fitness_Club_Membership', 'Beer', 'Monthly_Public_Transport',
       'Lunch', 'Large_apartment', 'Medium_apartment', 'Small_apartment',
       'cities', 'Description', 'Poblacion', 'Homosexuality_acceptance',
       'LGBT_adoption_rights', 'LGBT_homosexuality_rights',
       'LGBT_marriage_rights', 'VAT_Sales_Tax', 'Art_galleries',
       'Concert_venues', 'Museums', 'Sport_venues', 'Currency_for_urban_area',
       'GDP_per_capita_uno', 'Growth', 'GDP_per_capita_otro', 'Unemployment',
       'url'],
      dtype='object')

In [70]:
df11.drop(["url_uno"], axis=1, inplace=True)

In [71]:
df11.to_csv("../Data/tercer_web_scrapping.csv")

In [ ]:
## Lo que siguen son pruebas anteriores que debe ser eliminadas

In [ ]:
demo=[]
    
for i in url_list[1]:
    dicc_demogra={'Growth':'No hay dato','GDP_per_capita': 'No hay dato','Unemployment': 'No hay dato', 'url':i}
    try:
        res = requests.get(i)
        soup = BeautifulSoup(res.content,"html.parser")
        textaco = soup.findAll("div", {"class":"figureLabel___2OYTW"})
        dicc_demogra["Growth"] = textaco[2].getText()
    except:
        pass
                  
    try:
        dicc_demogra["GDP_per_capita"] = textaco[6].getText()
    except:
        pass
                  
    try:
        dicc_demogra["Unemployment"] = textaco[7].getText()
    except:
        pass
                
demo.append(dicc_demogra)

In [39]:
demo

[{'Growth': 'No hay dato',
  'GDP_per_capita': '$58,087',
  'Unemployment': '3%',
  'url': '/'}]

In [ ]:
url2= 'https://teleport.org/cities/zurich/','https://teleport.org/cities/adelaide/','https://teleport.org/cities/albuquerque/'

In [12]:
Growth_in_2015_2020 = funcion_growth(url_list)

In [13]:
len(Growth_in_2015_2020)

262

In [14]:
Growth_in_2015_2020

['5%',
 '7%',
 '7%',
 '9%',
 '3%',
 '4%',
 '-1%',
 '13%',
 '6%',
 '12%',
 '-2%',
 '10%',
 '6%',
 '16%',
 '5%',
 '8%',
 '80',
 '10%',
 '0%',
 '18%',
 '7%',
 '1%',
 '-1%',
 '16%',
 '7%',
 '0%',
 '1%',
 '82',
 '3%',
 '7%',
 '13%',
 '-1%',
 '2%',
 '0%',
 '2%',
 '13%',
 '0%',
 '4%',
 '7%',
 '4%',
 '1%',
 '5%',
 '43%',
 '1%',
 '6%',
 '-4%',
 '8%',
 '11%',
 '6%',
 '9%',
 '127%',
 '5%',
 '7%',
 '6%',
 '14%',
 '3%',
 '6%',
 '1%',
 '1%',
 '0%',
 '1%',
 '1%',
 '-4%',
 '-41%',
 '3%',
 '8%',
 '5%',
 '8%',
 '-2%',
 '4%',
 '11%',
 '34%',
 '10%',
 '7%',
 '7%',
 '-3%',
 '-39%',
 '1%',
 '12%',
 '4%',
 '1%',
 '2%',
 '10%',
 '1%',
 '2%',
 '-2%',
 '8%',
 '7%',
 '1%',
 '-1%',
 '0%',
 '7%',
 '1%',
 '0%',
 '5%',
 '-1%',
 '-1%',
 '5%',
 '3%',
 '1%',
 '0%',
 '-2%',
 '6%',
 '18%',
 '11%',
 '2%',
 '11%',
 '9%',
 '6%',
 '2%',
 '8%',
 '6%',
 '9%',
 '10%',
 '4%',
 '3%',
 '62%',
 '1%',
 '1%',
 '5%',
 '-1%',
 '10%',
 '-2%',
 '13%',
 '7%',
 '3%',
 '17%',
 '6%',
 '2%',
 '0%',
 '0%',
 '9%',
 '0%',
 '1%',
 '4%',
 '5%',
 '3%',
 '3%',
 '9%',
 '0%',
 '2%',
 '5%',
 '2%',
 '4%',
 '9%',
 '2%',
 '4%',
 '3%',
 '1%',
 '1%',
 '7%',
 '1%',
 '1%',
 '3%',
 '1%',
 '0%',
 '3%',
 '4%',
 '1%',
 '4%',
 '6%',
 '4%',
 '4%',
 '14%',
 '1%',
 '-4%',
 '3%',
 '-11%',
 '-1%',
 '-2%',
 '3%',
 '5%',
 '5%',
 '12%',
 '-1%',
 '7%',
 '7%',
 '6%',
 '5%',
 '1%',
 '9%',
 '2%',
 '7%',
 '0%',
 '12%',
 '13%',
 '36%',
 '-3%',
 '5%',
 '-3%',
 '0%',
 '8%',
 '-1%',
 '4%',
 '9%',
 '13%',
 '6%',
 '5%',
 '-3%',
 '2%',
 '12%',
 '-1%',
 '1%',
 '2%',
 '3%',
 '6%',
 '10%',
 '3%',
 '2%',
 '3%',
 '-3%',
 '3%',
 '-1%',
 '7%',
 '5%',
 '3%',
 '-1%',
 '9%',
 '4%',
 '5%',
 '-1%',
 '9%',
 '12%',
 '2%',
 '3%',
 '1%',
 '9%',
 '1%',
 '7%',
 '2%',
 '-5%',
 '7%',
 '6%',
 '-6%',
 '2%',
 '-2%',
 '5%',
 '8%',
 '4%',
 '-1%',
 '1%',
 '7%',
 '6%',
 '9%',
 '-1%',
 '3%',
 '7%',
 '6%',
 '0%',
 '1%',
 '7%',
 '3%',
 '4%',
 '1%',
 '2%',
 '5%',
 '4%',
 '3%',
 '-1%',
 '2%',
 '1%',
 '6%']

In [258]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
url_4 = 'https://teleport.org/cities/zurich/'
for i in url_4:
    driver.get(url_4)
    sleep(5)
    growth = driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div").text
        #container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div                                            
        #container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(14) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp
    print(growth)

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-258-10e955b4e852>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-258-10e955b4e852>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  growth = driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div").text

6%
6%
6%
6%
6%
6%

KeyboardInterrupt:

In [ ]:
##A partir de aca empiezan las variable Climate & Good Country Index

In [177]:
url_9 = 'https://teleport.org/cities/zurich/'

In [178]:
res = requests.get(url_9)

In [179]:
textaco = soup.findAll("span", {"class":"largeNr___3pgI2"})

In [ ]:
<span class="largeNr___3pgI2" data-reactid="3304">4</span>

In [180]:
textaco

[<span class="largeNr___3pgI2" data-reactid="3331">23</span>,
 <span class="largeNr___3pgI2" data-reactid="3340">26</span>,
 <span class="largeNr___3pgI2" data-reactid="3386">66</span>,
 <span class="largeNr___3pgI2" data-reactid="3432">34</span>,
 <span class="largeNr___3pgI2" data-reactid="3478">46</span>,
 <span class="largeNr___3pgI2" data-reactid="3524">53</span>,
 <span class="largeNr___3pgI2" data-reactid="3570">20</span>,
 <span class="largeNr___3pgI2" data-reactid="3616">12</span>]

In [ ]:
<div class="globalRank___1QMLG" data-reactid="3300"><img alt="Switzerland" src="/assets/firefly/flags/CH.svg" data-reactid="3301"><div data-reactid="3302"><b data-reactid="3303"><span class="largeNr___3pgI2" data-reactid="3304">4</span><!-- react-text: 3305 -->th<!-- /react-text --></b><!-- react-text: 3306 -->&nbsp;from a total of <!-- /react-text --><!-- react-text: 3307 -->163<!-- /react-text --><!-- react-text: 3308 --> countries<!-- /react-text --></div></div>

In [ ]:
#Esta es la funcion que funciono bien:

In [106]:
clima = []
for i in url_list:
    dicc_clima={'Climate':'No hay dato','url':i}
    try:
        res = requests.get(i)
        soup = BeautifulSoup(res.content,"html.parser")
        textaco = soup.findAll("div", {"class":"sunshine___16aRO"})
        dicc_clima["Climate"] = textaco[0].getText()
    except:
        pass
    clima.append(dicc_clima)

In [107]:
clima

[{'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/aarhus/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/adelaide/'},
 {'Climate': '168', 'url': 'https://teleport.org/cities/albuquerque/'},
 {'Climate': '64', 'url': 'https://teleport.org/cities/almaty/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/amsterdam/'},
 {'Climate': '61', 'url': 'https://teleport.org/cities/anchorage/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/andorra/'},
 {'Climate': '243', 'url': 'https://teleport.org/cities/ankara/'},
 {'Climate': '101', 'url': 'https://teleport.org/cities/asheville/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/asuncion/'},
 {'Climate': '266.7', 'url': 'https://teleport.org/cities/athens/'},
 {'Climate': '110', 'url': 'https://teleport.org/cities/atlanta/'},
 {'Climate': '182.9', 'url': 'https://teleport.org/cities/auckland/'},
 {'Climate': '116', 'url': 'https://teleport.org/cities/austin/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/baku/'},
 {'Climate': '207', 'url': 'https://teleport.org/cities/bali/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/baltimore/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/bangkok/'},
 {'Climate': '73', 'url': 'https://teleport.org/cities/barcelona/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/beijing/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/beirut/'},
 {'Climate': '209.5', 'url': 'https://teleport.org/cities/belfast/'},
 {'Climate': '75', 'url': 'https://teleport.org/cities/belgrade/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/bengaluru/'},
 {'Climate': '113', 'url': 'https://teleport.org/cities/bergen/'},
 {'Climate': '160', 'url': 'https://teleport.org/cities/berlin/'},
 {'Climate': '213', 'url': 'https://teleport.org/cities/bern/'},
 {'Climate': '35', 'url': 'https://teleport.org/cities/bilbao/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/birmingham/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/bogota/'},
 {'Climate': '120', 'url': 'https://teleport.org/cities/boise/'},
 {'Climate': '288', 'url': 'https://teleport.org/cities/bologna/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/bordeaux/'},
 {'Climate': '98', 'url': 'https://teleport.org/cities/boston/'},
 {'Climate': '324', 'url': 'https://teleport.org/cities/boulder/'},
 {'Climate': '326', 'url': 'https://teleport.org/cities/bozeman/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/bratislava/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/brighton/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/brisbane/'},
 {'Climate': '116', 'url': 'https://teleport.org/cities/bristol/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/brno/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/brussels/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/bucharest/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/budapest/'},
 {'Climate': '124', 'url': 'https://teleport.org/cities/buenos-aires/'},
 {'Climate': '54', 'url': 'https://teleport.org/cities/buffalo/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/cairo/'},
 {'Climate': '297.1', 'url': 'https://teleport.org/cities/calgary/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/cambridge/'},
 {'Climate': '254', 'url': 'https://teleport.org/cities/cape-town/'},
 {'Climate': '260', 'url': 'https://teleport.org/cities/caracas/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/cardiff/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/casablanca/'},
 {'Climate': '259', 'url': 'https://teleport.org/cities/charleston/'},
 {'Climate': '111', 'url': 'https://teleport.org/cities/charlotte/'},
 {'Climate': '105', 'url': 'https://teleport.org/cities/chattanooga/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/chennai/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/chiang-mai/'},
 {'Climate': '84', 'url': 'https://teleport.org/cities/chicago/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/chisinau/'},
 {'Climate': '238.3', 'url': 'https://teleport.org/cities/christchurch/'},
 {'Climate': '82', 'url': 'https://teleport.org/cities/cincinnati/'},
 {'Climate': '66', 'url': 'https://teleport.org/cities/cleveland/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/cluj-napoca/'},
 {'Climate': '138', 'url': 'https://teleport.org/cities/cologne/'},
 {'Climate': '127', 'url': 'https://teleport.org/cities/colorado-springs/'},
 {'Climate': '72', 'url': 'https://teleport.org/cities/columbus/'},
 {'Climate': '13', 'url': 'https://teleport.org/cities/copenhagen/'},
 {'Climate': '161', 'url': 'https://teleport.org/cities/cork/'},
 {'Climate': '228', 'url': 'https://teleport.org/cities/curitiba/'},
 {'Climate': '136', 'url': 'https://teleport.org/cities/dallas/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/dar-es-salaam/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/delhi/'},
 {'Climate': '115', 'url': 'https://teleport.org/cities/denver/'},
 {'Climate': '105', 'url': 'https://teleport.org/cities/des-moines/'},
 {'Climate': '76', 'url': 'https://teleport.org/cities/detroit/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/doha/'},
 {'Climate': '298', 'url': 'https://teleport.org/cities/dresden/'},
 {'Climate': '337', 'url': 'https://teleport.org/cities/dubai/'},
 {'Climate': '174', 'url': 'https://teleport.org/cities/dublin/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/dusseldorf/'},
 {'Climate': '227.8', 'url': 'https://teleport.org/cities/edinburgh/'},
 {'Climate': '288.2', 'url': 'https://teleport.org/cities/edmonton/'},
 {'Climate': '281', 'url': 'https://teleport.org/cities/eindhoven/'},
 {'Climate': '75', 'url': 'https://teleport.org/cities/eugene/'},
 {'Climate': '282', 'url': 'https://teleport.org/cities/florence/'},
 {'Climate': '225', 'url': 'https://teleport.org/cities/florianopolis/'},
 {'Climate': '330', 'url': 'https://teleport.org/cities/fort-collins/'},
 {'Climate': '302', 'url': 'https://teleport.org/cities/frankfurt/'},
 {'Climate': '90', 'url': 'https://teleport.org/cities/fukuoka/'},
 {'Climate': '181', 'url': 'https://teleport.org/cities/gdansk/'},
 {'Climate': '44', 'url': 'https://teleport.org/cities/geneva/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/gibraltar/'},
 {'Climate': '198', 'url': 'https://teleport.org/cities/glasgow/'},
 {'Climate': '13.2', 'url': 'https://teleport.org/cities/gothenburg/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/grenoble/'},
 {'Climate': '277.1', 'url': 'https://teleport.org/cities/guadalajara/'},
 {'Climate': '222', 'url': 'https://teleport.org/cities/guatemala-city/'},
 {'Climate': '200', 'url': 'https://teleport.org/cities/halifax/'},
 {'Climate': '13', 'url': 'https://teleport.org/cities/hamburg/'},
 {'Climate': '296', 'url': 'https://teleport.org/cities/hannover/'},
 {'Climate': '265', 'url': 'https://teleport.org/cities/havana/'},
 {'Climate': '13.3', 'url': 'https://teleport.org/cities/helsinki/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/ho-chi-minh-city/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/hong-kong/'},
 {'Climate': '90', 'url': 'https://teleport.org/cities/honolulu/'},
 {'Climate': '91', 'url': 'https://teleport.org/cities/houston/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/hyderabad/'},
 {'Climate': '88', 'url': 'https://teleport.org/cities/indianapolis/'},
 {'Climate': '281', 'url': 'https://teleport.org/cities/innsbruck/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/istanbul/'},
 {'Climate': '95', 'url': 'https://teleport.org/cities/jacksonville/'},
 {'Climate': '246', 'url': 'https://teleport.org/cities/jakarta/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/johannesburg/'},
 {'Climate': '121', 'url': 'https://teleport.org/cities/kansas-city/'},
 {'Climate': '285', 'url': 'https://teleport.org/cities/karlsruhe/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/kathmandu/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/kiev/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/kingston/'},
 {'Climate': '97', 'url': 'https://teleport.org/cities/knoxville/'},
 {'Climate': '217', 'url': 'https://teleport.org/cities/krakow/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/kuala-lumpur/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/kyoto/'},
 {'Climate': '312', 'url': 'https://teleport.org/cities/lagos/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/la-paz/'},
 {'Climate': '65',
  'url': 'https://teleport.org/cities/las-palmas-de-gran-canaria/'},
 {'Climate': '211', 'url': 'https://teleport.org/cities/las-vegas/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/lausanne/'},
 {'Climate': '91', 'url': 'https://teleport.org/cities/leeds/'},
 {'Climate': '290', 'url': 'https://teleport.org/cities/leipzig/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/lille/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/lima/'},
 {'Climate': '218', 'url': 'https://teleport.org/cities/lisbon/'},
 {'Climate': '89', 'url': 'https://teleport.org/cities/liverpool/'},
 {'Climate': '200', 'url': 'https://teleport.org/cities/ljubljana/'},
 {'Climate': '241.4', 'url': 'https://teleport.org/cities/london/'},
 {'Climate': '147', 'url': 'https://teleport.org/cities/los-angeles/'},
 {'Climate': '93', 'url': 'https://teleport.org/cities/louisville/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/luxembourg/'},
 {'Climate': '31', 'url': 'https://teleport.org/cities/lviv/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/lyon/'},
 {'Climate': '90', 'url': 'https://teleport.org/cities/madison/'},
 {'Climate': '94', 'url': 'https://teleport.org/cities/madrid/'},
 {'Climate': '107', 'url': 'https://teleport.org/cities/malaga/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/malmo/'},
 {'Climate': '252', 'url': 'https://teleport.org/cities/managua/'},
 {'Climate': '13', 'url': 'https://teleport.org/cities/manchester/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/manila/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/marseille/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/medellin/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/melbourne/'},
 {'Climate': '118', 'url': 'https://teleport.org/cities/memphis/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/mexico-city/'},
 {'Climate': '75', 'url': 'https://teleport.org/cities/miami/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/milan/'},
 {'Climate': '90', 'url': 'https://teleport.org/cities/milwaukee/'},
 {'Climate': '96',
  'url': 'https://teleport.org/cities/minneapolis-saint-paul/'},
 {'Climate': '13', 'url': 'https://teleport.org/cities/minsk/'},
 {'Climate': '302', 'url': 'https://teleport.org/cities/montevideo/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/montreal/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/moscow/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/mumbai/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/munich/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/nairobi/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/nantes/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/naples/'},
 {'Climate': '103', 'url': 'https://teleport.org/cities/nashville/'},
 {'Climate': '101', 'url': 'https://teleport.org/cities/new-orleans/'},
 {'Climate': '107', 'url': 'https://teleport.org/cities/new-york/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/nice/'},
 {'Climate': '336', 'url': 'https://teleport.org/cities/nicosia/'},
 {'Climate': '139', 'url': 'https://teleport.org/cities/oklahoma-city/'},
 {'Climate': '111', 'url': 'https://teleport.org/cities/omaha/'},
 {'Climate': '90', 'url': 'https://teleport.org/cities/orlando/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/osaka/'},
 {'Climate': '177', 'url': 'https://teleport.org/cities/oslo/'},
 {'Climate': '246.7', 'url': 'https://teleport.org/cities/ottawa/'},
 {'Climate': '13.5', 'url': 'https://teleport.org/cities/oulu/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/oxford/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/palo-alto/'},
 {'Climate': '102', 'url': 'https://teleport.org/cities/panama/'},
 {'Climate': '180', 'url': 'https://teleport.org/cities/paris/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/perth/'},
 {'Climate': '93', 'url': 'https://teleport.org/cities/philadelphia/'},
 {'Climate': '282', 'url': 'https://teleport.org/cities/phnom-penh/'},
 {'Climate': '211', 'url': 'https://teleport.org/cities/phoenix/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/phuket/'},
 {'Climate': '58', 'url': 'https://teleport.org/cities/pittsburgh/'},
 {'Climate': '68', 'url': 'https://teleport.org/cities/portland-or/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/porto/'},
 {'Climate': '242', 'url': 'https://teleport.org/cities/porto-alegre/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/prague/'},
 {'Climate': '99', 'url': 'https://teleport.org/cities/providence/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/quebec/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/quito/'},
 {'Climate': '111', 'url': 'https://teleport.org/cities/raleigh/'},
 {'Climate': '13.6', 'url': 'https://teleport.org/cities/reykjavik/'},
 {'Climate': '100', 'url': 'https://teleport.org/cities/richmond/'},
 {'Climate': '13.1', 'url': 'https://teleport.org/cities/riga/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/rio-de-janeiro/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/riyadh/'},
 {'Climate': '61', 'url': 'https://teleport.org/cities/rochester/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/rome/'},
 {'Climate': '130', 'url': 'https://teleport.org/cities/rotterdam/'},
 {'Climate': '13.3', 'url': 'https://teleport.org/cities/saint-petersburg/'},
 {'Climate': '125', 'url': 'https://teleport.org/cities/salt-lake-city/'},
 {'Climate': '106', 'url': 'https://teleport.org/cities/san-antonio/'},
 {'Climate': '147', 'url': 'https://teleport.org/cities/san-diego/'},
 {'Climate': '298',
  'url': 'https://teleport.org/cities/san-francisco-bay-area/'},
 {'Climate': '271', 'url': 'https://teleport.org/cities/san-jose/'},
 {'Climate': '70', 'url': 'https://teleport.org/cities/san-juan/'},
 {'Climate': '337', 'url': 'https://teleport.org/cities/san-luis-obispo/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/san-salvador/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/santiago/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/santo-domingo/'},
 {'Climate': '12.5', 'url': 'https://teleport.org/cities/sao-paulo/'},
 {'Climate': '236', 'url': 'https://teleport.org/cities/sarajevo/'},
 {'Climate': '299.5', 'url': 'https://teleport.org/cities/saskatoon/'},
 {'Climate': '71', 'url': 'https://teleport.org/cities/seattle/'},
 {'Climate': '250', 'url': 'https://teleport.org/cities/seoul/'},
 {'Climate': '129', 'url': 'https://teleport.org/cities/seville/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/shanghai/'},
 {'Climate': '147', 'url': 'https://teleport.org/cities/singapore/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/skopje/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/sofia/'},
 {'Climate': '101', 'url': 'https://teleport.org/cities/st-louis/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/stockholm/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/stuttgart/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/sydney/'},
 {'Climate': '161', 'url': 'https://teleport.org/cities/taipei/'},
 {'Climate': '13.2', 'url': 'https://teleport.org/cities/tallinn/'},
 {'Climate': '102', 'url': 'https://teleport.org/cities/tampa-bay-area/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/tampere/'},
 {'Climate': '236', 'url': 'https://teleport.org/cities/tartu/'},
 {'Climate': '113', 'url': 'https://teleport.org/cities/tashkent/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/tbilisi/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/tehran/'},
 {'Climate': '287', 'url': 'https://teleport.org/cities/tel-aviv/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/the-hague/'},
 {'Climate': 'No hay dato',
  'url': 'https://teleport.org/cities/thessaloniki/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/tokyo/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/toronto/'},
 {'Climate': '291', 'url': 'https://teleport.org/cities/toulouse/'},
 {'Climate': '12.7', 'url': 'https://teleport.org/cities/tunis/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/turin/'},
 {'Climate': '13.4', 'url': 'https://teleport.org/cities/turku/'},
 {'Climate': '13.3', 'url': 'https://teleport.org/cities/uppsala/'},
 {'Climate': 'No hay dato', 'url': 'https://teleport.org/cities/utrecht/'},
 {'Climate': '91', 'url': 'https://teleport.org/cities/valencia/'},
 {'Climate': '12.6', 'url': 'https://teleport.org/cities/valletta/'},
 {'Climate': '199.9', 'url': 'https://teleport.org/cities/vancouver/'},
 {'Climate': '213.1', 'url': 'https://teleport.org/cities/victoria/'},
 {'Climate': '172', 'url': 'https://teleport.org/cities/vienna/'},
 {'Climate': '49.4', 'url': 'https://teleport.org/cities/vilnius/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/warsaw/'},
 {'Climate': '97', 'url': 'https://teleport.org/cities/washington-dc/'},
 {'Climate': '180', 'url': 'https://teleport.org/cities/wellington/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/winnipeg/'},
 {'Climate': '12.9', 'url': 'https://teleport.org/cities/wroclaw/'},
 {'Climate': '286', 'url': 'https://teleport.org/cities/yerevan/'},
 {'Climate': '12.8', 'url': 'https://teleport.org/cities/zagreb/'},
 {'Climate': '36', 'url': 'https://teleport.org/cities/zurich/'}]

In [182]:
datos_clima = clima

In [184]:
df12 = pd.DataFrame(datos_clima)

In [186]:
df12.head()

       Climate                                       url
0  No hay dato       https://teleport.org/cities/aarhus/
1         12.6     https://teleport.org/cities/adelaide/
2          168  https://teleport.org/cities/albuquerque/
3           64       https://teleport.org/cities/almaty/
4         12.9    https://teleport.org/cities/amsterdam/

In [187]:
df11["Average_Annual_percent_sunshine"] = df12["Climate"]

In [188]:
df11.head()

,Airport_hub,Intercity_train_connectivity,Gun_related_deaths,Guns_per_residents,Pisa_ranking,Best_university,Monthly_Fitness_Club_Membership,Beer,Monthly_Public_Transport,Lunch,...,Concert_venues,Museums,Sport_venues,Currency_for_urban_area,GDP_per_capita_uno,Growth,GDP_per_capita_otro,Unemployment,url,Average_Annual_percent_sunshine
0,8,0.59,1,12,13,Aarhus University,$37.00,$1.70,$62.00,$15.00,...,95,18,21,DKK,$44342.66,5%,"$44,343",4%,https://teleport.org/cities/aarhus/,No hay dato
1,26,0.17,1,24,16,University of Adelaide,$50.00,$4.30,$80.00,$13.00,...,89,37,91,AUD,$46433.30,7%,"$46,433",6%,https://teleport.org/cities/adelaide/,12.6
2,23,0.11,16,328,24,University of New Mexico,$52.00,$2.90,$37.00,$12.00,...,99,35,10,USD,$54596.65,7%,"$54,597",5%,https://teleport.org/cities/albuquerque/,168
3,45,0.66,1,1,39,427.97,$83.00,$0.68,$19.00,$5.70,...,68,24,53,KZT,$24019.95,9%,"$24,020",6%,https://teleport.org/cities/almaty/,64
4,237,0.68,1,4,10,University of Amsterdam,$49.00,$2.10,$100.00,$18.00,...,339,187,154,EUR,$47354.53,3%,"$47,355",6%,https://teleport.org/cities/amsterdam/,12.9

In [189]:
df11.to_csv("../Data/ultimo_web_scrapping.csv")

In [122]:
GDP=[]
    
for i in url_list:
    dicc_gdp={'Overall_info': 'No hay dato','World_order': 'No hay dato', 'url':i}
  
    try:
        res = requests.get(i)
        soup = BeautifulSoup(res.content,"html.parser")
        textaco2 = soup.findAll("div", {"class":"largeNr___3pgI2"})
        dicc_gdp["Overall_info"] = textaco2[0].getText()
    except:
        pass
                  
    try:
        dicc_gdp["World_order"] = textaco2[7].getText()
    except:
        pass
                
    GDP.append(dicc_gdp)

In [123]:
GDP

[{'Overall_info': '2', 'url': 'https://teleport.org/cities/aarhus/'},
 {'Overall_info': '18', 'url': 'https://teleport.org/cities/adelaide/'},
 {'Overall_info': '23', 'url': 'https://teleport.org/cities/albuquerque/'}]

In [220]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

#Climate
#Good Country Index
pop_demo2 = []

for i in url_list[:3]:
    driver.get(i)
    sleep(5)
    dicc_demo ={"Climate_type" :"No hay dato",
               "Overall_ranking":"No hay dato",
                "World_order": "No hay dato"
                "url":i}
    #Climate
    try:
        clima_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(18) > div.contents___3CJmK > div.overview___1ziR0 > div:nth-child(3) > div").text
        dicc_demo["Climate_type"] = clima_info
        driver.implicitly_wait(20)  
    except:
        pass

    #Good Country Index
    try:
        overall_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(24) > div:nth-child(3) > div.globalRank___1QMLG > div > b > span").text
        dicc_demo["Overall_ranking"] = overall_info
        driver.implicitly_wait(20)
    except:
        pass
    try:
        world_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(24) > div:nth-child(3) > div.categories___2-Cu0 > div:nth-child(1) > b > span").text
        dicc_demo["World_order"] = world_info
        driver.implicitly_wait(20)         
    except:
        pass

    pop_demo2.append(dicc_demo)   
    
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-220-a57883a27758>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-220-a57883a27758>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  clima_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(18) > div.contents___3CJmK > div.overview___1ziR0 > div:nth-child(3) > div").text
<ipython-input-220-a57883a27758>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  overall_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(24) > div:nth-child(3) > div.globalRank___1QMLG > div > b > span").text
<ipython-input-220-a57883a27758>:30: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  world_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(24) > div:nth-child(3) > div.categories___2-Cu0 > div:nth-child(1) > b > span").text

In [221]:
pop_demo2

[{'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/aarhus/'},
 {'Climate_type': 'MEDITERRANEAN',
  'Overall_ranking': '18',
  'World_order': '9',
  'url': 'https://teleport.org/cities/adelaide/'},
 {'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/albuquerque/'}]

In [259]:
driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)

#Population/Demographics
#Climate
#Good Country Index
pop_demo = []


for i in url_list[:5]:
    driver.get(i)
    sleep(5)
    dicc_demo ={"Growth_in_2015_2020" :"No hay dato",
               "url":i}
    
    try:
        growth_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div").text
        dicc_demo["Growth_in_2015_2020"] = growth_info
        print(growth_info)
        driver.implicitly_wait(20)
    except:
        pass

    pop_demo.append(dicc_demo)   
    
driver.quit()

====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/Users/danielaarias/.wdm/drivers/chromedriver/mac64/96.0.4664.45/chromedriver] found in cache
<ipython-input-259-737dca8af70e>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), options = opciones)
<ipython-input-259-737dca8af70e>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  growth_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div").text

7%
9%
3%

In [235]:
pop_demo

[{'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/aarhus/'},
 {'Growth_in_2015_2020': '7%',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/adelaide/'},
 {'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/albuquerque/'}]

In [ ]:
#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(14) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div > span
#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(16) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div > span
#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(1) > div:nth-child(3) > div.figure___1kD9P > div.figureContents___3h4Xp > div > span

In [ ]:
        
        try:
            Unemployment_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(2) > div > div:nth-child(5) > div.figureContents___3h4Xp > div.figureLabel___2OYTW > span").text
            dicc_demo["Unemployment"] = Unemployment_info
            driver.implicitly_wait(20)
        except:
            pass
        
        try:
            Languages_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(15) > div:nth-child(3) > section:nth-child(3) > div > div:nth-child(2) > div.languages___asRqx > span").text
            dicc_demo["Languages"] = Languages_info
            driver.implicitly_wait(20)
        except:
            pass

        #Climate
        try:
            clima_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(18) > div.contents___3CJmK > div.overview___1ziR0 > div:nth-child(3) > div").text
            dicc_demo["Climate_type"] = clima_info
            driver.implicitly_wait(20)  
        except:
            pass

        #Good Country Index
        try:
            overall_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(24) > div:nth-child(3) > div.globalRank___1QMLG > div > b > span").text
            dicc_demo["Overall_ranking"] = overall_info
            driver.implicitly_wait(20)
        except:
            pass
        try:
            world_info=driver.find_element_by_css_selector("#container > div > main > div > div.contents___1nRSJ > div > div.container___3R5n9 > article:nth-child(24) > div:nth-child(3) > div.categories___2-Cu0 > div:nth-child(1) > b > span").text
            dicc_demo["World_order"] = world_info
            driver.implicitly_wait(20)         
        except:
            pass

In [126]:
data_web = pop_demo

In [128]:
segundo = pd.DataFrame(data_web)

In [129]:
segundo.head()

,Population,Growth_in_2015_2020,Unemployment,Languages,Climate_type,Overall_ranking,World_order,url
0,No hay dato,No hay dato,No hay dato,No hay dato,No hay dato,No hay dato,No hay dato,https://teleport.org/cities/aarhus/
1,"1,708,700",7%,6%,English,MEDITERRANEAN,18,9,https://teleport.org/cities/adelaide/
2,No hay dato,No hay dato,No hay dato,No hay dato,No hay dato,No hay dato,No hay dato,https://teleport.org/cities/albuquerque/
3,"2,029,800",9%,6%,Russian,HOT SUMMER CONTINENTAL,No hay dato,No hay dato,https://teleport.org/cities/almaty/
4,"2,628,100",3%,6%,Dutch,MARINE WEST COAST,No hay dato,No hay dato,https://teleport.org/cities/amsterdam/

In [137]:
pop_demo

[{'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/aarhus/'},
 {'Population': '1,708,700',
  'Growth_in_2015_2020': '7%',
  'Unemployment': '6%',
  'Languages': 'English',
  'Climate_type': 'MEDITERRANEAN',
  'Overall_ranking': '18',
  'World_order': '9',
  'url': 'https://teleport.org/cities/adelaide/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/albuquerque/'},
 {'Population': '2,029,800',
  'Growth_in_2015_2020': '9%',
  'Unemployment': '6%',
  'Languages': 'Russian',
  'Climate_type': 'HOT SUMMER CONTINENTAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/almaty/'},
 {'Population': '2,628,100',
  'Growth_in_2015_2020': '3%',
  'Unemployment': '6%',
  'Languages': 'Dutch',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/amsterdam/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': '23',
  'World_order': '26',
  'url': 'https://teleport.org/cities/anchorage/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/andorra/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/ankara/'},
 {'Population': '112,400',
  'Growth_in_2015_2020': '6%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/asheville/'},
 {'Population': '2,385,900',
  'Growth_in_2015_2020': '12%',
  'Unemployment': '6%',
  'Languages': 'No hay dato',
  'Climate_type': 'HUMID SUBTROPICAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/asuncion/'},
 {'Population': '3,868,500',
  'Growth_in_2015_2020': '-2%',
  'Unemployment': '25%',
  'Languages': 'No hay dato',
  'Climate_type': 'MEDITERRANEAN',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/athens/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/atlanta/'},
 {'Population': '1,359,700',
  'Growth_in_2015_2020': '6%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': '14',
  'World_order': '19',
  'url': 'https://teleport.org/cities/auckland/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/austin/'},
 {'Population': '1,512,400',
  'Growth_in_2015_2020': '5%',
  'Unemployment': '6%',
  'Languages': 'Azerbaijani',
  'Climate_type': 'TROPICAL AND SUBTROPICAL STEPPE',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/baku/'},
 {'Population': '1,356,600',
  'Growth_in_2015_2020': '8%',
  'Unemployment': '6%',
  'Languages': 'Indonesian',
  'Climate_type': 'TROPICAL SAVANNA',
  'Overall_ranking': '102',
  'World_order': '62',
  'url': 'https://teleport.org/cities/bali/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/baltimore/'},
 {'Population': '9,052,100',
  'Growth_in_2015_2020': '10%',
  'Unemployment': '1%',
  'Languages': 'Thai',
  'Climate_type': 'TROPICAL SAVANNA',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bangkok/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': '19',
  'World_order': '22',
  'url': 'https://teleport.org/cities/barcelona/'},
 {'Population': '12,377,000',
  'Growth_in_2015_2020': '18%',
  'Unemployment': '4%',
  'Languages': 'Chinese',
  'Climate_type': 'HOT SUMMER CONTINENTAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/beijing/'},
 {'Population': '3,176,800',
  'Growth_in_2015_2020': '7%',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'MEDITERRANEAN',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/beirut/'},
 {'Population': '344,600',
  'Growth_in_2015_2020': '1%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/belfast/'},
 {'Population': '1,737,800',
  'Growth_in_2015_2020': '-1%',
  'Unemployment': '19%',
  'Languages': 'Serbian',
  'Climate_type': 'HUMID SUBTROPICAL',
  'Overall_ranking': '45',
  'World_order': '48',
  'url': 'https://teleport.org/cities/belgrade/'},
 {'Population': '5,498,100',
  'Growth_in_2015_2020': '16%',
  'Unemployment': '8%',
  'Languages': 'English',
  'Climate_type': 'TROPICAL SAVANNA',
  'Overall_ranking': '64',
  'World_order': '100',
  'url': 'https://teleport.org/cities/bengaluru/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bergen/'},
 {'Population': '8,690,300',
  'Growth_in_2015_2020': '0%',
  'Unemployment': '4%',
  'Languages': 'German',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/berlin/'},
 {'Population': '233,100',
  'Growth_in_2015_2020': '1%',
  'Unemployment': '3%',
  'Languages': 'German',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bern/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bilbao/'},
 {'Population': '2,715,300',
  'Growth_in_2015_2020': '3%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': '5',
  'World_order': '14',
  'url': 'https://teleport.org/cities/birmingham/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': '74',
  'World_order': '122',
  'url': 'https://teleport.org/cities/bogota/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/boise/'},
 {'Population': '521,100',
  'Growth_in_2015_2020': '-1%',
  'Unemployment': '11%',
  'Languages': 'Italian',
  'Climate_type': 'HUMID SUBTROPICAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bologna/'},
 {'Population': '774,800',
  'Growth_in_2015_2020': '2%',
  'Unemployment': '10%',
  'Languages': 'French',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bordeaux/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/boston/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/boulder/'},
 {'Population': '54,600',
  'Growth_in_2015_2020': '13%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'WARM SUMMER CONTINENTAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bozeman/'},
 {'Population': '489,100',
  'Growth_in_2015_2020': '0%',
  'Unemployment': '10%',
  'Languages': 'Slovak',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bratislava/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/brighton/'},
 {'Population': '4,093,300',
  'Growth_in_2015_2020': '7%',
  'Unemployment': '6%',
  'Languages': 'English',
  'Climate_type': 'HUMID SUBTROPICAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/brisbane/'},
 {'Population': '781,300',
  'Growth_in_2015_2020': '4%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': '5',
  'World_order': '14',
  'url': 'https://teleport.org/cities/bristol/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/brno/'},
 {'Population': '2,429,800',
  'Growth_in_2015_2020': '5%',
  'Unemployment': '8%',
  'Languages': 'Dutch',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/brussels/'},
 {'Population': '4,592,600',
  'Growth_in_2015_2020': '43%',
  'Unemployment': '7%',
  'Languages': 'Romanian',
  'Climate_type': 'HUMID SUBTROPICAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/bucharest/'},
 {'Population': '4,936,300',
  'Growth_in_2015_2020': '1%',
  'Unemployment': '7%',
  'Languages': 'Hungarian',
  'Climate_type': 'WARM SUMMER CONTINENTAL',
  'Overall_ranking': '25',
  'World_order': '50',
  'url': 'https://teleport.org/cities/budapest/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': '56',
  'World_order': '39',
  'url': 'https://teleport.org/cities/buenos-aires/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/buffalo/'},
 {'Population': '10,660,900',
  'Growth_in_2015_2020': '8%',
  'Unemployment': '13%',
  'Languages': 'Arabic',
  'Climate_type': 'TROPICAL AND SUBTROPICAL DESERT',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cairo/'},
 {'Population': '1,066,700',
  'Growth_in_2015_2020': '11%',
  'Unemployment': '7%',
  'Languages': 'English',
  'Climate_type': 'CONTINENTAL SUBARCTIC',
  'Overall_ranking': '12',
  'World_order': '8',
  'url': 'https://teleport.org/cities/calgary/'},
 {'Population': '162,300',
  'Growth_in_2015_2020': '6%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cambridge/'},
 {'Population': '3,943,400',
  'Growth_in_2015_2020': '9%',
  'Unemployment': '27%',
  'Languages': 'No hay dato',
  'Climate_type': 'MEDITERRANEAN',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cape-town/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/caracas/'},
 {'Population': '484,300',
  'Growth_in_2015_2020': '5%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': '5',
  'World_order': '14',
  'url': 'https://teleport.org/cities/cardiff/'},
 {'Population': '3,144,900',
  'Growth_in_2015_2020': '7%',
  'Unemployment': '10%',
  'Languages': 'French',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/casablanca/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/charleston/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': '23',
  'World_order': '26',
  'url': 'https://teleport.org/cities/charlotte/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/chattanooga/'},
 {'Population': '6,020,700',
  'Growth_in_2015_2020': '6%',
  'Unemployment': '8%',
  'Languages': 'English',
  'Climate_type': 'TROPICAL SAVANNA',
  'Overall_ranking': '64',
  'World_order': '100',
  'url': 'https://teleport.org/cities/chennai/'},
 {'Population': '201,000',
  'Growth_in_2015_2020': '1%',
  'Unemployment': '1%',
  'Languages': 'Thai',
  'Climate_type': 'TROPICAL SAVANNA',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/chiang-mai/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/chicago/'},
 {'Population': '650,900',
  'Growth_in_2015_2020': '0%',
  'Unemployment': '6%',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/chisinau/'},
 {'Population': '383,100',
  'Growth_in_2015_2020': '1%',
  'Unemployment': '5%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/christchurch/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cincinnati/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cleveland/'},
 {'Population': '349,500',
  'Growth_in_2015_2020': '-41%',
  'Unemployment': '7%',
  'Languages': 'Romanian',
  'Climate_type': 'WARM SUMMER CONTINENTAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cluj-napoca/'},
 {'Population': '1,941,600',
  'Growth_in_2015_2020': '3%',
  'Unemployment': '4%',
  'Languages': 'German',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cologne/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/colorado-springs/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/columbus/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/copenhagen/'},
 {'Population': '190,400',
  'Growth_in_2015_2020': '-2%',
  'Unemployment': '8%',
  'Languages': 'English',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/cork/'},
 {'Population': '2,049,100',
  'Growth_in_2015_2020': '4%',
  'Unemployment': '13%',
  'Languages': 'Portuguese',
  'Climate_type': 'MARINE WEST COAST',
  'Overall_ranking': '46',
  'World_order': '42',
  'url': 'https://teleport.org/cities/curitiba/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/dallas/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',
  'Climate_type': 'No hay dato',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/dar-es-salaam/'},
 {'Population': '15,703,900',
  'Growth_in_2015_2020': '10%',
  'Unemployment': '8%',
  'Languages': 'English',
  'Climate_type': 'HUMID SUBTROPICAL',
  'Overall_ranking': 'No hay dato',
  'World_order': 'No hay dato',
  'url': 'https://teleport.org/cities/delhi/'},
 {'Population': 'No hay dato',
  'Growth_in_2015_2020': 'No hay dato',
  'Unemployment': 'No hay dato',
  'Languages': 'No hay dato',